openapi: 3.1.0
info:
  title: Cloud Integration Specification
  contact:
    name: ONVIF Technical Specification
    url: https://github.com/onvif/specs
    email: help@onvif.org
  license:
    name: ONVIF Contributor License Agreement
    url: https://github.com/onvif/specs/blob/development/LICENSE.md
  version: "24.12"

components:
  schemas:
    Base64DERencodedASN1Value:
      description: This schema is the equivalent of tas:Base64DERencodedASN1Value in the Security Service specification.
      type: object
      properties:
        Value:
          type: string
          format: byte
      required:
        - Value

    EndpointReferenceType:
      description: This schema is the equivalent of wsa:EndpointReferenceType in the WA-Addressing 1.0 specification.
      type: object
      properties:
        Address:
          type: string
          format: uri
      required:
        - Address

    DeviceConfiguration:
      type: object
      properties:
        ShareToken:
          description: The share token, to prove permission to share the device.
          item:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'
        EndpointReferences:
          description: The endpoint to be notified to inform that the operation was completed. It may be more then one if the requesting cloud has redundant URIs to receive the notification.
          items:
            $ref: '#/components/schemas/EndpointReferenceType'

    DeviceInformation:
      type: object
      properties:
        ShareToken:
          description: The share token, to know what device the public key is associated to.
          item:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'
        DevicePublicKey:
          description: The public key of the device.
          item:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'

    JWTConfiguration:
      type: object
      properties:
        Audiences:
          description: The list of all the aud claims, which the recipient identifies with.
          type: array
          items:
            type: string
        TrustedIssuers:
          description: If present, this is the list to URIs pointing to the metadata file conforming to RFC8414, such as "https://your.domain/.well-known/openid-configuration" , of the trusted Open ID Connect servers issuing JWT tokens. Using metadata, the device can reach the information about the JWKS and implement the rotation of the keys accordingly.
          type: array
          items:
            type: string
            format: uri
        JWTCertificate:
          description: The certificate holding the public ECC key used to validate JWTs.
          items:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'
        JWTTrustAnchor:
          description: The certificate with the public key used to validate the TLS certificate of the OIDC server.
          items:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'
      required:
        - Audiences

    UplinkConfiguration:
      type: object
      properties:
        RemoteAddress:
          description: Uniform resource locator by which the remote client can be reached.
          type: string
          format: uri
        UserLevel:
          description: Authorization level that will be assigned to the uplink connection.
          type: string
          enum: [Administrator, Operator, User]
        UplinkTrustAnchor:
          items:
            $ref: '#/components/schemas/Base64DERencodedASN1Value'
          description: The certificate with the public key used to validate the TLS certificate of the uplink server.
      required:
        - RemoteAddress
        - UserLevel

    startDeviceSharing:
      type: object
      properties:
        CamerasConfiguration:
          items:
            $ref: '#/components/schemas/DeviceConfiguration'
          description: For each camera requested to be shared, it is necessary to pass both the shared token and the endpoint reference.
        JWTConfiguration:
          items:
            $ref: '#/components/schemas/JWTConfiguration'
          description: Configuration of JWT authentication.
        UplinkConfiguration:
          items:
            $ref: '#/components/schemas/UplinkConfiguration'
          description: Configuration of the uplink service.
      required:
        - CamerasConfiguration
        - JWTConfiguration
        - UplinkConfiguration

    deviceSharingCompleted:
      type: object
      properties:
        DevicesInformation:
          items:
            $ref: '#/components/schemas/DeviceInformation'
          description: For each shared device, the share token and the public key will be provided.
      required:
        - DevicesInformation

paths:
  /startDeviceSharing:
    post:
      description: This operation triggers sharing a device with a new Operational Cloud Service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/startDeviceSharing'
      responses:
        '200':
          description: Success
        '400':
          description: Invalid Argument Value

  /deviceSharingCompleted:
    post:
      description: This operation notifies the new Operational Cloud Service that the camera was successfully configured.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deviceSharingCompleted'
      responses:
        '200':
          description: Success
