openapi: 3.0.3
info:
  title: Storage Configuration Renewal
  contact:
    name: ONVIF Technical Specification
    url: https://github.com/onvif/specs
    email: help@onvif.org
  license:
    name: ONVIF Contributor License Agreement
    url: https://github.com/onvif/specs/blob/development/LICENSE.md
  version: "24.12"
paths:
  /Configuration-Renewal:
    get:
      responses:
        '200':
          description: successful operation
          content:       
            application/vnd.onvif.storageconfiguration.renewal+json:
              schema:
                $ref: '#/components/schemas/storageConfigurationRenewal'
components:
  schemas:
    storageConfigurationRenewal:
      type: object
      required:
      - type
      properties:
        type:
          type: string
          example: "ObjectStorageS3"
          description: "tds:StorageType lists the available storage types for this property."
        region:
          type: string
          example: "us-east-1"
          description: "Optional region of the storage server"
        localPath:
          type: string
          example: null
          description: "Local Path"
        storageUri:
          type: string
          example: "https://<bucket>.s3.us-east-1.amazonaws.com/"
          description: "Storage server address"
        user:
          type: object
          description: "User credentials for the storage server"
          properties:
            username:
              type: string
              example: "<AccessKeyId>"
              description: "Optional user name used to access the storage server"
            password:
              type: string
              example: "<SecretAccessKey>"
              description: "Optional password used to access the storage server"
            token:
              type: string
              example: null
              description: "Optional token used to access the storage server"
        expiresAt:
          type: string
          example: "2024-08-14T15:31:24Z"
          description: "Expiration date of the storage configuration as an ISO 8601 date-time"