openapi: 3.0.3
info:
  title: Storage Configuration Renewal
  contact:
    name: ONVIF Technical Specification
    url: https://github.com/onvif/specs
    email: help@onvif.org
  license:
    name: ONVIF Contributor License Agreement
    url: https://github.com/onvif/specs/blob/development/LICENSE.md
  version: "24.12"
paths:
  /Configuration-Renewal:
    get:
      responses:
        '200':
          description: successful operation
          content:       
            application/vnd.onvif.storageconfiguration.renewal+json:
              schema:
                $ref: '#/components/schemas/storageConfigurationRenewal'
components:
  schemas:
    storageConfigurationRenewal:
      type: object
      required:
      - type
      properties:
        type:
          type: string
          example: "ObjectStorageS3"
        region:
          type: string
          example: "us-east-1"
        localPath:
          type: string
          example: null
        storageUri:
          type: string
          example: "https://<bucket>.s3.us-east-1.amazonaws.com/"
        user:
          type: object
          properties:
            username:
              type: string
              example: "<AccessKeyId>"
            password:
              type: string
              example: "<SecretAccessKey>"
            token:
              type: string
              example: null